apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
type: Opaque
stringData:
  PORT: "3000"
  MONGO_URI: "mongodb+srv://shamil880699:2pH5RvQ0kbTNCWKV@cluster0.awlgf5p.mongodb.net/authDB"
  JWT_SECRET: "supersecretkey"
  NODE_ENV: "production"

  EMAIL_USER: "shamil880699@gmail.com"
  EMAIL_PASSWORD: "tibk auao okky lvhi"
  EMAIL_SECRET: "nestEveEmail"

  KAFKA_BROKER: "kafka-srv:9092"
  FRONTEND_URL: "https://nest-eve-client.vercel.app"

  BUCKET_NAME: "nesteve-profile-bucket"
  BUCKET_REGION: "eu-north-1"
  BUCKET_ACCESS_KEY: "AKIAR46MJ5IAPEICEY64"
  BUCKET_SECRET_ACCESS_KEY: "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"

  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
